<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  
  '{minute}min' => '',
  '{minute}min {second}s' => '',
  '{minute}mins' => '',
  '{minute}mins {second}s' => '',
  '1 hour' => '1小时',
  'About us' => '关于本站',

  '{minute} minute' => '{minute}分',
  '{minute} minute {second} seconds' => '{minute}分{second}秒',
  '{minute} minutes' => '{minute}分',
  '{minute} minutes {second} seconds' => '{minute}分{second}秒',
  '{personName}\'s {year} Annual Summary' => '{personName}的{year}年度总结',
  '{year} Annual Summary' => '{year}年度总结',



  'Carpool' => '拼车',
  'carpool china' => '溢起拼车',
  'Are you sure you want to delete it?' => '您是否确定删除？',
);
